# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='messenger_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
