# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='subtitle',
            field=models.TextField(null=True),
        ),
    ]
